### ISSUE TITLE
Module not found `Error: Can't resolve 'https'`

### ISSUE THREAD

**Issue by andreia-oca** [Genez-io/genezio#151]
I am trying to run the `todo-list` app from the [genezio examples]().

`genezio local` runs successfully, but when I am trying to start the frontend with `npm start`, I am receiving the following errors:
```
ERROR in ./src/sdk/remote.js 7:0-26
Module not found: Error: Can't resolve 'https' in '/home/andreia/genezio-examples/javascript/todo-list/client/src/sdk'
```
and
```
ERROR in ./src/sdk/remote.js 8:0-24
Module not found: Error: Can't resolve 'http' in '/home/andreia/genezio-examples/javascript/todo-list/client/src/sdk'
```

I will leave below the contents of my `genezio.yaml` config file:
```
name: todo-list
region: us-east-1
sdk:
  language: js
  options:
    runtime: node
  path: ../client/src/sdk
frontend:
  path: ../client/build
classes:
  - path: ./task.js
    type: jsonrpc
    methods: []
  - path: ./user.js
    type: jsonrpc
    methods: []
```

It seems to me that the SDK was not generated correctly. Do you have any idea how to fix it?
