### ISSUE TITLE
[Improvement task]: "scripts" should also have an array of commands

### ISSUE THREAD

**Issue by vladiulianbogdan** [Genez-io/genezio#487]
### Describe your task

The "scripts" property from `genezio.yaml` is a way to run various commands at certain events that occur during the deployment: `preBackendDeploy`, `postBackendDeploy`, `preFrontendDeploy`, `postFrontendDeploy`. For example, one can specify that the `npm install` command should be executed before the execution of the deployment.

Right now, if a user wants to run multiple commands, we use && between them. Example:

```
scripts: 
  preFrontendDeploy: npm run install-prod-sdk && npm install && npm run build 
```
However, this is problematic because this is not cross platform.

I propose to have each hook be either a `string` or an `string[]`. The `YamlScriptsConfiguration` would become:

```
export class YamlScriptsConfiguration {
  preBackendDeploy?: string|string[];
  postBackendDeploy?: string|string[];
  postFrontendDeploy?: string|string[];
  preFrontendDeploy?: string|string[];
}
``` 

Then the scripts can be written like this:

```
scripts: 
  preFrontendDeploy:
    - npm run install-prod-sdk
    - npm install
    - npm run build 
```

**Comment by costinsin** [comment]
Related to this, I think we should think about introducing scripts per environment. For example, this is how it would look like in a workspace environment:

```yaml
workspace:
  backend:
    path: server
    scripts:
      preDeploy: npm install
      preStartLocal: 
        - npm install
        - echo 'Local started'
      postDeploy: echo Done
  frontend:
    path: client
    scripts:
      preDeploy:
        - npm install
        - npm run build
```
